Document alternate port for development
Turns out that Windows prevents the use of port `8000`.  To see the list of Windows' restricted ports:

```
C:\users> netsh interface ipv4 show excludedportrange protocol=tcp
Protocol tcp Port Exclusion Ranges
Start Port    End Port
----------    --------
      1035        1134
      1135        1234
...
      7781        7880
      7981        8080
      8081        8180
```

Otherwise, you will get an error similar to:

```
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```